services:
  server:
    build:
      context: .
      dockerfile: deploy/server.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/log/server_logs/temperature.log:/app/.logs/temperature.log
    restart: always
  cmd_migrations:
    build:
      context: .
      dockerfile: deploy/cmd_migrations.Dockerfile
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  cmd_food_to_db:
    build:
      context: .
      dockerfile: deploy/cmd_food_to_db.Dockerfile
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"


  cmd_server_health:
    build:
      context: .
      dockerfile: deploy/cmd_server_health.Dockerfile
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
