# Generated by Django 5.1.7 on 2025-03-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelServerHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disk_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disk_free', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_5_avg_cpu_load_perc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_10_avg_cpu_load_perc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_15_avg_cpu_load_perc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memory_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memory_free', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Server Health',
            },
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(blank=True, null=True)),
                ('brands', models.CharField(blank=True, null=True)),
                ('countries', models.CharField(blank=True, null=True)),
                ('energy_kcal_100g', models.IntegerField(blank=True, null=True)),
                ('carbohydrates_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('proteins_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fat_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fiber_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sugars_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('salt_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saturated_fat_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('code', models.CharField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_name', 'brands'], name='myfood_food_product_06ce14_idx'), models.Index(fields=['product_name', 'brands', 'countries'], name='myfood_food_product_588669_idx'), models.Index(fields=['code'], name='myfood_food_code_1b277c_idx'), models.Index(fields=['product_name'], name='myfood_food_product_fbf4fe_idx'), models.Index(fields=['brands'], name='myfood_food_brands_a3c0cc_idx')],
            },
        ),
    ]
