# Generated by Django 5.0.7 on 2024-07-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
