# Generated by Django 5.0.7 on 2024-07-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0002_alter_sitestatus_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.CharField(default='What to generate?', max_length=4096)),
                ('image_number', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(default='1024x1024', max_length=32)),
                ('request_seconds', models.FloatField(blank=True, null=True)),
                ('image_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
