# Generated by Django 5.0.7 on 2024-07-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0003_openaiimagegeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiimagegeneration',
            name='image_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
