# Generated by Django 5.0.7 on 2024-07-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0004_openaiimagegeneration_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disk_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disk_free', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='openaiimagegeneration',
            name='size',
            field=models.CharField(choices=[('256x256', '256x256'), ('512x512', '512x512'), ('1024x1024', '1024x1024'), ('1792x1024', '1792x1024')], default='256x256', max_length=32),
        ),
    ]
