# Generated by Django 5.0.7 on 2024-07-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0006_alter_serverhealth_options_alter_sitestatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverhealth',
            name='min_10_avg_cpu_load_perc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='serverhealth',
            name='min_15_avg_cpu_load_perc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='serverhealth',
            name='min_5_avg_cpu_load_perc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
