# Generated by Django 5.0.7 on 2024-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0008_serverhealth_memory_free_serverhealth_memory_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=2048)),
            ],
            options={
                'verbose_name_plural': 'Links',
            },
        ),
    ]
