# Generated by Django 5.0.7 on 2024-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0009_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiimagegeneration',
            name='use_dalle3',
            field=models.BooleanField(default=False),
        ),
    ]
