# Generated by Django 5.0.7 on 2024-07-21 15:20

import myfood.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0010_openaiimagegeneration_use_dalle3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('s3_file', models.FileField(storage=myfood.storages.S3Storage, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='openaiimagegeneration',
            name='size',
            field=models.CharField(choices=[('256x256', '256x256'), ('512x512', '512x512'), ('1024x1024', '1024x1024'), ('1792x1024', '1792x1024')], default='256x256', help_text='If Dalle3-E model is used the size can be only 1024x1024', max_length=32),
        ),
    ]
