# Generated by Django 5.0.7 on 2024-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0012_lumagenerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumagenerate',
            name='in_generation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='lumagenerate',
            name='last_result_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
