# Generated by Django 5.0.7 on 2024-07-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0014_remove_lumagenerate_in_generation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageUpload',
            new_name='ModelImageUpload',
        ),
        migrations.RenameModel(
            old_name='Link',
            new_name='ModelLink',
        ),
        migrations.RenameModel(
            old_name='LumaGenerate',
            new_name='ModelLumaGenerate',
        ),
        migrations.RenameModel(
            old_name='OpenAIImageGeneration',
            new_name='ModelOpenAIImageGeneration',
        ),
        migrations.RenameModel(
            old_name='ServerHealth',
            new_name='ModelServerHealth',
        ),
    ]
