# Generated by Django 5.0.7 on 2024-07-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0015_rename_imageupload_modelimageupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellumagenerate',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
