# Generated by Django 5.0.7 on 2024-07-24 18:01

import myfood.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0016_modellumagenerate_authenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelopenaiimagegeneration',
            old_name='image_link',
            new_name='openai_temp_image_link',
        ),
        migrations.AddField(
            model_name='modelopenaiimagegeneration',
            name='s3_generated_image',
            field=models.FileField(blank=True, null=True, storage=myfood.storages.S3Storage, upload_to=''),
        ),
    ]
