# Generated by Django 5.0.7 on 2024-07-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0018_remove_modelopenaiimagegeneration_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(choices=[], default='gpt-4o-mini', max_length=50)),
                ('system_message', models.CharField(default='You are a helpful assistant.', max_length=2048)),
                ('user_input', models.CharField(max_length=8192)),
                ('model_answer', models.CharField(max_length=8192)),
                ('usage_prompt_tokens', models.PositiveIntegerField()),
                ('usage_completion_tokens', models.PositiveIntegerField()),
                ('usage_total_tokens', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='modelopenaiimagegeneration',
            name='image_resolution',
            field=models.CharField(choices=[('256x256', 's256x256'), ('512x512', 's512x512'), ('1024x1024', 's1024x1024'), ('1792x1024', 's1792x1024')], default='256x256', help_text='If Dalle3-E model is used the resolution can be only 1024x1024', max_length=32),
        ),
    ]
