# Generated by Django 5.0.7 on 2024-07-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0019_modelchat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelchat',
            name='response_time',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
