# Generated by Django 5.0.7 on 2024-07-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0020_modelchat_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelchat',
            name='model_answer',
            field=models.TextField(max_length=8192),
        ),
        migrations.AlterField(
            model_name='modelchat',
            name='system_message',
            field=models.TextField(default='You are a helpful assistant.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='modelchat',
            name='user_input',
            field=models.TextField(max_length=8192),
        ),
    ]
