# Generated by Django 5.0.7 on 2024-07-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0022_alter_modelopenaiimagegeneration_image_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelopenaiimagegeneration',
            name='image_resolution',
            field=models.CharField(choices=[('256x256', 's256x256'), ('512x512', 's512x512'), ('1024x1024', 's1024x1024'), ('1792x1024', 's1792x1024')], default='256x256', help_text='If Dalle3-E model is used the resolution can be only 1024x1024', max_length=32),
        ),
    ]
