# Generated by Django 5.0.7 on 2024-07-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0023_alter_modelopenaiimagegeneration_image_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelchat',
            name='model',
            field=models.CharField(choices=[('gpt-4o-mini', 'gpt-4o-mini'), ('gpt-4o', 'gpt-4o')], default='gpt-4o-mini', max_length=50),
        ),
    ]
