# Generated by Django 5.0.7 on 2024-07-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0024_alter_modelchat_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelopenaiimagegeneration',
            name='image_resolution',
            field=models.CharField(choices=[('256x256', '256x256'), ('512x512', '512x512'), ('1024x1024', '1024x1024'), ('1792x1024', '1792x1024')], default='256x256', help_text='If Dalle3-E model is used the resolution can be only 1024x1024', max_length=32),
        ),
    ]
