# Generated by Django 5.0.7 on 2024-10-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myfood', '0025_alter_modelopenaiimagegeneration_image_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carbohydrates_100g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "cholesterol",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=6, null=True
                    ),
                ),
                ("brands", models.CharField(blank=True, null=True)),
                ("code", models.CharField(blank=True, null=True)),
                ("categories", models.CharField(blank=True, null=True)),
                (
                    "completeness",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("countries", models.CharField(blank=True, null=True)),
                ("created_datetime", models.DateTimeField(blank=True, null=True)),
                ("creator", models.CharField(blank=True, null=True)),
                ("energy_kcal_100g", models.IntegerField(blank=True, null=True)),
                ("energy_100g", models.IntegerField(blank=True, null=True)),
                (
                    "fat_100g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "fiber_100g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "image_ingredients_small_url",
                    models.CharField(blank=True, null=True),
                ),
                ("image_ingredients_url", models.CharField(blank=True, null=True)),
                ("image_nutrition_small_url", models.CharField(blank=True, null=True)),
                ("image_nutrition_url", models.CharField(blank=True, null=True)),
                ("image_small_url", models.CharField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, null=True)),
                ("ingredients_analysis_tags", models.CharField(blank=True, null=True)),
                ("ingredients_tags", models.CharField(blank=True, null=True)),
                (
                    "iron_100g",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=6, null=True
                    ),
                ),
                ("last_modified_by", models.CharField(blank=True, null=True)),
                ("last_modified_datetime", models.DateTimeField(blank=True, null=True)),
                ("last_updated_datetime", models.DateTimeField(blank=True, null=True)),
                ("main_category", models.CharField(blank=True, null=True)),
                ("nutrition_levels_tags", models.CharField(blank=True, null=True)),
                ("nutriscore_grade", models.CharField(blank=True, null=True)),
                ("nutriscore_score", models.IntegerField(blank=True, null=True)),
                ("pnns_groups_1", models.CharField(blank=True, null=True)),
                ("pnns_groups_2", models.CharField(blank=True, null=True)),
                ("popularity_tags", models.CharField(blank=True, null=True)),
                ("product_name", models.CharField(blank=True, null=True)),
                (
                    "proteins_100g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "salt_100g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "saturated_fat_100g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("serving_size", models.CharField(blank=True, null=True)),
                ("serving_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "sugars_100g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "vitamin_c_100g",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=6, null=True
                    ),
                ),
                (
                    "vitamin_a_100g",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=6, null=True
                    ),
                ),
                ("url", models.CharField(blank=True, null=True)),
            ],
        ),
    ]
