# Generated by Django 5.0.7 on 2024-10-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myfood', "0026_foodproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodproduct",
            name="quantity",
            field=models.CharField(blank=True, null=True),
        ),
    ]
