# Generated by Django 5.0.7 on 2024-10-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myfood", "0027_alter_foodproduct_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodproduct",
            name="carbohydrates_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="foodproduct",
            name="completeness",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="foodproduct",
            name="fat_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="foodproduct",
            name="fiber_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="foodproduct",
            name="proteins_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="foodproduct",
            name="salt_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="foodproduct",
            name="saturated_fat_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="foodproduct",
            name="sugars_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
