# Generated by Django 5.0.7 on 2024-10-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myfood', "0028_alter_foodproduct_carbohydrates_100g_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodproduct",
            name="serving_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
