# Generated by Django 5.0.7 on 2024-10-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myfood', "0029_alter_foodproduct_serving_quantity"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="foodproduct",
            index=models.Index(
                fields=["product_name", "brands"], name="me_foodprod_product_bde803_idx"
            ),
        ),
    ]

# Ho