# Generated by Django 5.0.7 on 2024-10-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "myfood",
            "0031_rename_me_foodprod_product_bde803_idx_myfood_food_product_06ce14_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="foodproduct",
            index=models.Index(
                fields=["product_name", "brands", "countries"],
                name="myfood_food_product_588669_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="foodproduct",
            index=models.Index(fields=["code"], name="myfood_food_code_1b277c_idx"),
        ),
    ]
