# Generated by Django 5.0.7 on 2024-10-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myfood", "0032_foodproduct_myfood_food_product_588669_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="foodproduct",
            index=models.Index(
                fields=["product_name"], name="myfood_food_product_fbf4fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodproduct",
            index=models.Index(fields=["brands"], name="myfood_food_brands_a3c0cc_idx"),
        ),
    ]
