name: Deploy Prod My-food backend
env:
  MYFOOD_CSV_LINK: ${{ vars.MYFOOD_CSV_LINK }}
  MYFOOD_DATABASE_HOST: ${{ vars.MYFOOD_DATABASE_HOST }}
  MYFOOD_DATABASE_PORT: ${{ vars.MYFOOD_DATABASE_PORT }}
  MYFOOD_DATABASE_NAME: ${{ vars.MYFOOD_DATABASE_NAME }}
  MYFOOD_DATABASE_USER: ${{ vars.MYFOOD_DATABASE_USER }}
  MYFOOD_DATABASE_PASS: ${{ vars.MYFOOD_DATABASE_PASS }}
  MYFOOD_DEBUG: ${{ vars.MYFOOD_DEBUG }}
  MYFOOD_DJANGO_SECRET_KEY: ${{ vars.MYFOOD_DJANGO_SECRET_KEY }}
  MYFOOD_ENVIRONMENT: ${{ vars.MYFOOD_ENVIRONMENT }}
  

run-name: ${{ github.event.head_commit.message }}
on:
  push
jobs:
  me-deployment:
    runs-on: hostinger-backend-runner
    environment: prod
    name: Deploy to prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Store env vars in file
        run: env | grep MYFOOD > .env

      - name: Build all docker images
        run: sudo docker compose build django fastapi golang caddy cmd_migrations django_tests

      - name: Run tests
        run: sudo docker compose run --rm django_tests

      - name: Apply migrations
        run: sudo docker compose run cmd_migrations

      - name: Restart service
        run: sudo docker compose up --detach django caddy fastapi golang

